/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import dao.DanhMucDAO;
import entity.DanhMucEntity;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Tran Tien
 */
public class QuanLyDanhMucJPanel extends javax.swing.JPanel {

    // ✅ Tạo đối tượng DAO để thao tác với database (thêm, sửa, xóa, lấy danh sách)
    DanhMucDAO danhMucDao = new DanhMucDAO();

    // ✅ Hàm khởi tạo JPanel — chạy đầu tiên khi mở form
    public QuanLyDanhMucJPanel() {
        initComponents(); // Tự động tạo UI (giao diện) từ NetBeans Design
        fillTable();       // Gọi hàm đổ dữ liệu từ database lên bảng
    }

    // ✅ Hàm này lấy dữ liệu từ CSDL và đổ lên bảng tblDanhMuc
    public void fillTable() {
        // Ép kiểu model của JTable để có thể thao tác thêm dòng/xóa dòng
        DefaultTableModel model = (DefaultTableModel) tblDanhMuc.getModel();
        model.setRowCount(0); // Xóa tất cả dữ liệu cũ trong bảng

        // Lặp qua danh sách danh mục lấy từ database
        for (DanhMucEntity danhmuc : danhMucDao.getAll()) {
            Object data[] = {
                danhmuc.getMaDanhMuc(), // Lấy mã danh mục
                danhmuc.getTenDanhMuc(), // Lấy tên danh mục
                danhmuc.getMoTa()        // Lấy mô tả danh mục
            };
            model.addRow(data); // Thêm 1 dòng mới vào bảng
        }

        // Gán model đã cập nhật lại cho bảng
        tblDanhMuc.setModel(model);
    }

    // ✅ Lấy thông tin từ các ô nhập (TextField) để tạo ra đối tượng DanhMucEntity
    public DanhMucEntity getDanhMuc() {
        try {
            int maDM = 1; // Nếu ô mã danh mục trống, mặc định là 1 (hoặc bỏ qua nếu tự tăng)
            if (!txtMaDanhMuc.getText().isEmpty()) {
                maDM = Integer.parseInt(txtMaDanhMuc.getText()); // Ép kiểu từ chuỗi sang số
            }

            // Lấy tên danh mục từ ô nhập
            String tenDM = txtTenDanhMuc.getText();

            // Lấy mô tả từ ô nhập
            String moTa = txtMoTa.getText();

            // Trả về 1 đối tượng DanhMucEntity chứa thông tin người dùng nhập
            return new DanhMucEntity(maDM, tenDM, moTa);

        } catch (Exception e) {
            // Nếu có lỗi (ví dụ: nhập chữ vào ô số), in lỗi ra console
            System.out.println("Lỗi get danh mục: " + e.getMessage());
            return null;
        }
    }

    // ✅ Hiển thị thông tin danh mục lên form khi người dùng chọn 1 dòng trên bảng
    public void setDanhMuc(DanhMucEntity danhMuc) {
        txtMaDanhMuc.setText(String.valueOf(danhMuc.getMaDanhMuc())); // Hiển thị mã
        txtTenDanhMuc.setText(danhMuc.getTenDanhMuc());               // Hiển thị tên
        txtMoTa.setText(danhMuc.getMoTa());                           // Hiển thị mô tả
    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhMuc = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaDanhMuc = new javax.swing.JTextField();
        txtTenDanhMuc = new javax.swing.JTextField();
        txtMoTa = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(255, 153, 204));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã Danh Mục");

        tblDanhMuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MaDanhMuc", "TenDanhMuc", "MoTa", "TrangThai"
            }
        ));
        jScrollPane1.setViewportView(tblDanhMuc);

        jLabel2.setText("Tên Danh Mục");

        jLabel3.setText("Mô Tả");

        jLabel5.setText("DANH MỤC");

        jLabel4.setText("TrangThai");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Còn bán", "Ngừng bán", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtTenDanhMuc))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtMaDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(42, 42, 42)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(47, 47, 47))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(24, 24, 24))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(btnThem)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSua)
                                    .addGap(24, 24, 24)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(273, 273, 273)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtMaDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtTenDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // Lấy dữ liệu từ form, tạo ra 1 đối tượng danh mục
        this.danhMucDao.insert(this.getDanhMuc()); // Gọi DAO để thêm vào database

        // Thông báo cho người dùng biết thêm thành công
        JOptionPane.showMessageDialog(btnThem, "Thêm danh mục thành công");

        // Gọi lại fillTable() để cập nhật bảng hiển thị danh sách mới nhất
        fillTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
         // Lấy dữ liệu trên form, đưa vào DAO để cập nhật trong database
        this.danhMucDao.update(this.getDanhMuc());

        // Hiển thị thông báo
        JOptionPane.showMessageDialog(btnThem, "Sửa danh mục thành công");

        // Làm mới lại bảng hiển thị
        fillTable();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
         // Lấy chuỗi nhập trong ô mã danh mục
        String maDMStr = txtMaDanhMuc.getText().trim();

        // Nếu người dùng chưa nhập mã
        if (maDMStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hoặc nhập Mã Danh Mục để xoá.");
            return; // Dừng lại, không chạy tiếp
        }

        try {
            // Ép kiểu từ chuỗi sang số nguyên
            int maDanhMuc = Integer.parseInt(maDMStr);

            // Gọi hàm xóa trong DAO
            danhMucDao.delete(maDanhMuc);

            // Thông báo xóa thành công
            JOptionPane.showMessageDialog(this, "Xoá danh mục thành công!");

            // Làm mới lại bảng sau khi xóa
            this.fillTable();

        } catch (NumberFormatException e) {
            // Nếu người dùng nhập ký tự không phải số
            JOptionPane.showMessageDialog(this, "Mã danh mục không hợp lệ!");
        }
    }//GEN-LAST:event_btnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDanhMuc;
    private javax.swing.JTextField txtMaDanhMuc;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtTenDanhMuc;
    // End of variables declaration//GEN-END:variables
}
