/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.ChiTietHoaDonDAO;
import dao.HoaDonDAO;
import entity.ChiTietHoaDonEntity;
import entity.HoaDonEntity;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tran Tien
 */
public class QuanLyHoaDonJPanel extends javax.swing.JPanel {

    HoaDonDAO hoaDonDAO = new HoaDonDAO();
    ChiTietHoaDonDAO chiTietHoaDonDAO = new ChiTietHoaDonDAO();

    /**
     * Creates new form HoaDonJPanel
     */
    public QuanLyHoaDonJPanel() {
        initComponents();
        fillTable();
        fillTableChiTietHoaDon();
    }

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
        model.setRowCount(0);

        List<HoaDonEntity> list = hoaDonDAO.getAll();
        DecimalFormat df = new DecimalFormat("#,### VNĐ");

        for (HoaDonEntity hd : list) {
            Object[] data = {
                hd.getIdHoaDon(),
                hd.getTenKhachHang(), //!= null ? hd.getTenKhachHang() : "Khách lẻ"
                hd.getNgayLap(),
                df.format(hd.getTongTien()),
                hd.getTrangThai()
            };
            model.addRow(data);
        }
    }

    private void fillTableChiTietHoaDon() {
        DefaultTableModel model = (DefaultTableModel) tblChiTietHoaDon.getModel();
        model.setRowCount(0);

        // Lấy danh sách chi tiết hóa đơn theo id hóa đơn đang chọn
        List<ChiTietHoaDonEntity> list = chiTietHoaDonDAO.getAll();

        // Tạo DecimalFormat để format số
        DecimalFormat df = new DecimalFormat("#,###");

        for (ChiTietHoaDonEntity ct : list) {
            double thanhTien = ct.getSoLuong() * ct.getDonGia();

            String donGiaStr = df.format(ct.getDonGia());
            String thanhTienStr = df.format(ct.getThanhTien()); // dùng getThanhTien() mới

            model.addRow(new Object[]{
                ct.getIdChiTietHoaDon(),
                ct.getTenSanPham(),
                ct.getTenDanhMuc(),
                ct.getTenMauSac(),
                ct.getTenKichThuoc(),
                ct.getSoLuong(),
                donGiaStr,
                thanhTienStr
            });
        }
    }

//        public HoaDonEntity getHoaDon() {
//        try {
//            int maHD = 0;
//            if (!txtMaHD.getText().isEmpty()) {
//                maHD = Integer.parseInt(txtMaHD.getText());
//            }
//            String ngayTao = txtNgayTao.getText().trim();
//            double tongTien = Double.parseDouble(txtTongTien.getText().trim());
//            String trangThai = cboTrangThai.getSelectedItem().toString();
//            String nhanVien = txtNhanVien.getText().trim();
//            String khachHang = txtKhachHang.getText().trim();
//
//            if (ngayTao.isEmpty() || nhanVien.isEmpty()) {
//                JOptionPane.showMessageDialog(this, "Không được để trống Ngày tạo hoặc Nhân viên!");
//                return null;
//            }
//
//            return new HoaDonEntity(maHD, ngayTao, tongTien, trangThai, nhanVien, khachHang);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Lỗi nhập liệu: " + e.getMessage());
//            return null;
//        }
//    }
//          public void setHoaDon(HoaDonEntity hd) {
//        txtMaHD.setText(String.valueOf(hd.getIdHoaDon()));
//        txtNgayTao.setText(hd.getNgayLap());
//        txtTongTien.setText(String.valueOf(hd.getTongTien()));
//        cboTrangThai.setSelectedItem(hd.getTrangThai());
//        txtNhanVien.setText(hd.());
//        txtKhachHang.setText(hd.getKhachHang());
//    }  
//        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtTimKiemHoaDon = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChiTietHoaDon = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        btnCapNhat = new javax.swing.JButton();

        label1.setText("label1");

        jPanel1.setBackground(new java.awt.Color(255, 153, 204));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Hóa đơn");

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        tblChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID sản phẩm", "Tên sản phẩm", "Danh mục", "Màu sắc", "Kích thước", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblChiTietHoaDon);

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Hóa đơn", "Tên Khách hàng", "Ngày lập", "Tổng tiền", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        jScrollPane3.setViewportView(jScrollPane1);

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTimKiemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCapNhat))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem)
                    .addComponent(txtTimKiemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addContainerGap(475, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String input = txtTimKiemHoaDon.getText().trim();

// Kiểm tra ô nhập có trống không
        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ID hóa đơn!");
            txtTimKiemHoaDon.requestFocus();
            return;
        }

// Kiểm tra nhập phải số
        int idHoaDon;
        try {
            idHoaDon = Integer.parseInt(input);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "ID hóa đơn phải là số!");
            txtTimKiemHoaDon.requestFocus();
            return;
        }

// Tìm hóa đơn theo ID
        HoaDonEntity hd = hoaDonDAO.getById(idHoaDon);
        if (hd == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy hóa đơn với ID: " + idHoaDon);
            return;
        }

// ✅ Xóa bảng chỉ khi tìm thấy dữ liệu hợp lệ
        DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
        model.setRowCount(0);

// Hiển thị kết quả lên bảng
        Object[] data = {
            hd.getIdHoaDon(),
            hd.getTenKhachHang(),
            hd.getNgayLap(),
            hd.getTongTien(),
            hd.getTrangThai()
        };
        model.addRow(data);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
        model.setRowCount(0); // xóa tất cả dữ liệu trong bảng
        this.fillTable();
    }//GEN-LAST:event_btnCapNhatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label1;
    private javax.swing.JTable tblChiTietHoaDon;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtTimKiemHoaDon;
    // End of variables declaration//GEN-END:variables
}
